/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_formdev_flatlaf_ui_FlatNativeLibrary */

#ifndef _Included_com_formdev_flatlaf_ui_FlatNativeLibrary
#define _Included_com_formdev_flatlaf_ui_FlatNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_formdev_flatlaf_ui_FlatNativeLibrary
 * Method:    getApiVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_formdev_flatlaf_ui_FlatNativeLibrary_getApiVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
