/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_formdev_flatlaf_ui_FlatNativeMacLibrary */

#ifndef _Included_com_formdev_flatlaf_ui_FlatNativeMacLibrary
#define _Included_com_formdev_flatlaf_ui_FlatNativeMacLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_formdev_flatlaf_ui_FlatNativeMacLibrary
 * Method:    setWindowRoundedBorder
 * Signature: (Ljava/awt/Window;FFI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_formdev_flatlaf_ui_FlatNativeMacLibrary_setWindowRoundedBorder
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
