/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_formdev_flatlaf_ui_FlatNativeLinuxLibrary */

#ifndef _Included_com_formdev_flatlaf_ui_FlatNativeLinuxLibrary
#define _Included_com_formdev_flatlaf_ui_FlatNativeLinuxLibrary
#ifdef __cplusplus
extern "C" {
#endif
#undef com_formdev_flatlaf_ui_FlatNativeLinuxLibrary_MOVE
#define com_formdev_flatlaf_ui_FlatNativeLinuxLibrary_MOVE 8L
/*
 * Class:     com_formdev_flatlaf_ui_FlatNativeLinuxLibrary
 * Method:    xMoveOrResizeWindow
 * Signature: (Ljava/awt/Window;III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_formdev_flatlaf_ui_FlatNativeLinuxLibrary_xMoveOrResizeWindow
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_formdev_flatlaf_ui_FlatNativeLinuxLibrary
 * Method:    xShowWindowMenu
 * Signature: (Ljava/awt/Window;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_formdev_flatlaf_ui_FlatNativeLinuxLibrary_xShowWindowMenu
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
